# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\MainWindow\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 26))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuStudent = QtWidgets.QMenu(self.menubar)
        self.menuStudent.setObjectName("menuStudent")
        self.menuFees = QtWidgets.QMenu(self.menubar)
        self.menuFees.setObjectName("menuFees")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_User = QtWidgets.QAction(MainWindow)
        self.actionAdd_User.setObjectName("actionAdd_User")
        self.actionDelete_User = QtWidgets.QAction(MainWindow)
        self.actionDelete_User.setObjectName("actionDelete_User")
        self.actionChange_Password = QtWidgets.QAction(MainWindow)
        self.actionChange_Password.setObjectName("actionChange_Password")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionStudent_File = QtWidgets.QAction(MainWindow)
        self.actionStudent_File.setObjectName("actionStudent_File")
        self.actionFees_Form = QtWidgets.QAction(MainWindow)
        self.actionFees_Form.setObjectName("actionFees_Form")
        self.actionRepost_Form = QtWidgets.QAction(MainWindow)
        self.actionRepost_Form.setObjectName("actionRepost_Form")
        self.menuTools.addAction(self.actionAdd_User)
        self.menuTools.addAction(self.actionDelete_User)
        self.menuTools.addAction(self.actionChange_Password)
        self.menuTools.addAction(self.actionLogin)
        self.menuStudent.addAction(self.actionStudent_File)
        self.menuFees.addAction(self.actionFees_Form)
        self.menuReport.addAction(self.actionRepost_Form)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuStudent.menuAction())
        self.menubar.addAction(self.menuFees.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuStudent.setTitle(_translate("MainWindow", "Student"))
        self.menuFees.setTitle(_translate("MainWindow", "Fees"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.actionAdd_User.setText(_translate("MainWindow", "Add_User"))
        self.actionDelete_User.setText(_translate("MainWindow", "Delete_User"))
        self.actionChange_Password.setText(_translate("MainWindow", "Change_Password"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionStudent_File.setText(_translate("MainWindow", "Student_Form"))
        self.actionFees_Form.setText(_translate("MainWindow", "Fees_Form"))
        self.actionRepost_Form.setText(_translate("MainWindow", "Report_Form"))
