# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Student\StudentForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 131, 21))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 91, 21))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 91, 21))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 200, 131, 21))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 131, 31))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 330, 131, 21))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.txtStudentName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtStudentName.setGeometry(QtCore.QRect(190, 30, 221, 31))
        self.txtStudentName.setObjectName("txtStudentName")
        self.radMale = QtWidgets.QRadioButton(self.centralwidget)
        self.radMale.setGeometry(QtCore.QRect(190, 80, 71, 21))
        self.radMale.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radMale.setObjectName("radMale")
        self.radFemale = QtWidgets.QRadioButton(self.centralwidget)
        self.radFemale.setGeometry(QtCore.QRect(330, 80, 81, 21))
        self.radFemale.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radFemale.setObjectName("radFemale")
        self.cmbSubject = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSubject.setGeometry(QtCore.QRect(190, 130, 221, 31))
        self.cmbSubject.setObjectName("cmbSubject")
        self.txtMonthlyFee = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMonthlyFee.setGeometry(QtCore.QRect(190, 200, 221, 31))
        self.txtMonthlyFee.setObjectName("txtMonthlyFee")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(190, 260, 221, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.cmbBatch = QtWidgets.QComboBox(self.centralwidget)
        self.cmbBatch.setGeometry(QtCore.QRect(190, 320, 221, 31))
        self.cmbBatch.setObjectName("cmbBatch")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Name"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.label_3.setText(_translate("MainWindow", "Subject"))
        self.label_4.setText(_translate("MainWindow", "Monthly Fee"))
        self.label_5.setText(_translate("MainWindow", "Starting From"))
        self.label_6.setText(_translate("MainWindow", "Batch"))
        self.radMale.setText(_translate("MainWindow", "Male"))
        self.radFemale.setText(_translate("MainWindow", "Female"))
