# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Yearly_Report\Yearly_Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 426)
        MainWindow.setStyleSheet("background-color: rgb(255, 219, 198);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(18, 9, 101, 31))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btnShow = QtWidgets.QPushButton(self.centralwidget)
        self.btnShow.setGeometry(QtCore.QRect(248, 9, 93, 31))
        self.btnShow.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnShow.setObjectName("btnShow")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(18, 49, 611, 351))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.cmbYear = QtWidgets.QComboBox(self.centralwidget)
        self.cmbYear.setGeometry(QtCore.QRect(140, 10, 91, 31))
        self.cmbYear.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.cmbYear.setObjectName("cmbYear")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        self.cmbYear.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Year "))
        self.btnShow.setText(_translate("MainWindow", "Show"))
        self.cmbYear.setItemText(0, _translate("MainWindow", "2000"))
        self.cmbYear.setItemText(1, _translate("MainWindow", "2001"))
        self.cmbYear.setItemText(2, _translate("MainWindow", "2002"))
        self.cmbYear.setItemText(3, _translate("MainWindow", "2003"))
        self.cmbYear.setItemText(4, _translate("MainWindow", "2004"))
        self.cmbYear.setItemText(5, _translate("MainWindow", "2005"))
        self.cmbYear.setItemText(6, _translate("MainWindow", "2006"))
        self.cmbYear.setItemText(7, _translate("MainWindow", "2007"))
        self.cmbYear.setItemText(8, _translate("MainWindow", "2008"))
        self.cmbYear.setItemText(9, _translate("MainWindow", "2009"))
        self.cmbYear.setItemText(10, _translate("MainWindow", "2010"))
        self.cmbYear.setItemText(11, _translate("MainWindow", "2011"))
        self.cmbYear.setItemText(12, _translate("MainWindow", "2012"))
        self.cmbYear.setItemText(13, _translate("MainWindow", "2013"))
        self.cmbYear.setItemText(14, _translate("MainWindow", "2014"))
        self.cmbYear.setItemText(15, _translate("MainWindow", "2015"))
        self.cmbYear.setItemText(16, _translate("MainWindow", "2016"))
        self.cmbYear.setItemText(17, _translate("MainWindow", "2017"))
        self.cmbYear.setItemText(18, _translate("MainWindow", "2018"))
        self.cmbYear.setItemText(19, _translate("MainWindow", "2019"))
        self.cmbYear.setItemText(20, _translate("MainWindow", "2020"))
        self.cmbYear.setItemText(21, _translate("MainWindow", "2021"))
        self.cmbYear.setItemText(22, _translate("MainWindow", "2022"))
        self.cmbYear.setItemText(23, _translate("MainWindow", "2023"))
        self.cmbYear.setItemText(24, _translate("MainWindow", "2024"))
        self.cmbYear.setItemText(25, _translate("MainWindow", "2025"))
        self.cmbYear.setItemText(26, _translate("MainWindow", "2026"))
