# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Delete_User\Delete_User.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 112)
        MainWindow.setStyleSheet("background-color: rgb(255, 164, 254);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 100, 21))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.cmbselectuser = QtWidgets.QComboBox(self.centralwidget)
        self.cmbselectuser.setGeometry(QtCore.QRect(110, 10, 231, 31))
        self.cmbselectuser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbselectuser.setObjectName("cmbselectuser")
        self.btndelete = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete.setGeometry(QtCore.QRect(110, 60, 111, 28))
        self.btndelete.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.btndelete.setObjectName("btndelete")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(232, 60, 111, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select User"))
        self.btndelete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
