# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python_Code\user_Project\Change_Password\Change_Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 31))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 101, 31))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 91, 31))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 91, 31))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.cmbusername = QtWidgets.QComboBox(self.centralwidget)
        self.cmbusername.setGeometry(QtCore.QRect(170, 40, 221, 31))
        self.cmbusername.setObjectName("cmbusername")
        self.txtoldpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtoldpassword.setGeometry(QtCore.QRect(170, 100, 221, 31))
        self.txtoldpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtoldpassword.setObjectName("txtoldpassword")
        self.txtpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword.setGeometry(QtCore.QRect(170, 160, 221, 31))
        self.txtpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword.setObjectName("txtpassword")
        self.txtpassword1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword1.setGeometry(QtCore.QRect(170, 220, 221, 31))
        self.txtpassword1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword1.setObjectName("txtpassword1")
        self.btnchange = QtWidgets.QPushButton(self.centralwidget)
        self.btnchange.setGeometry(QtCore.QRect(80, 290, 93, 28))
        self.btnchange.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnchange.setObjectName("btnchange")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 290, 93, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.label_2.setText(_translate("MainWindow", "Old Password"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.btnchange.setText(_translate("MainWindow", "Change "))
        self.pushButton_2.setText(_translate("MainWindow", "Close "))
