# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Fees\Fees.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 284)
        MainWindow.setStyleSheet("background-color: rgb(237, 255, 171);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 161, 31))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 240, 81, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget1.setGeometry(QtCore.QRect(440, 10, 621, 261))
        self.tableWidget1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(0)
        self.tableWidget1.setRowCount(0)
        self.dateedit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit.setGeometry(QtCore.QRect(190, 70, 241, 31))
        self.dateedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateedit.setCalendarPopup(True)
        self.dateedit.setObjectName("dateedit")
        self.btndelete1 = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete1.setGeometry(QtCore.QRect(270, 240, 71, 28))
        self.btndelete1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btndelete1.setObjectName("btndelete1")
        self.btnsave1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnsave1.setGeometry(QtCore.QRect(90, 240, 81, 28))
        self.btnsave1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnsave1.setObjectName("btnsave1")
        self.btnupdate1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnupdate1.setGeometry(QtCore.QRect(180, 240, 81, 28))
        self.btnupdate1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnupdate1.setObjectName("btnupdate1")
        self.txtfees = QtWidgets.QLineEdit(self.centralwidget)
        self.txtfees.setGeometry(QtCore.QRect(190, 130, 241, 31))
        self.txtfees.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtfees.setObjectName("txtfees")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 101, 31))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 101, 31))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 101, 31))
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.btnnew1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnnew1.setGeometry(QtCore.QRect(10, 240, 71, 28))
        self.btnnew1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnnew1.setObjectName("btnnew1")
        self.cmbselectstudent = QtWidgets.QComboBox(self.centralwidget)
        self.cmbselectstudent.setGeometry(QtCore.QRect(190, 10, 241, 31))
        self.cmbselectstudent.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbselectstudent.setObjectName("cmbselectstudent")
        self.txtsubject = QtWidgets.QLineEdit(self.centralwidget)
        self.txtsubject.setGeometry(QtCore.QRect(190, 190, 241, 31))
        self.txtsubject.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtsubject.setObjectName("txtsubject")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Student Name"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
        self.btndelete1.setText(_translate("MainWindow", "Delete"))
        self.btnsave1.setText(_translate("MainWindow", "Save"))
        self.btnupdate1.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "Date"))
        self.label_3.setText(_translate("MainWindow", "Fees"))
        self.label_4.setText(_translate("MainWindow", "Subject"))
        self.btnnew1.setText(_translate("MainWindow", "New"))
