# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Fees\Fees.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1381, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 31))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 280, 61, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget1.setGeometry(QtCore.QRect(510, 10, 831, 331))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(0)
        self.tableWidget1.setRowCount(0)
        self.dateedit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit.setGeometry(QtCore.QRect(210, 90, 261, 31))
        self.dateedit.setCalendarPopup(True)
        self.dateedit.setObjectName("dateedit")
        self.btndelete1 = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete1.setGeometry(QtCore.QRect(320, 280, 61, 28))
        self.btndelete1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btndelete1.setObjectName("btndelete1")
        self.btnsave1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnsave1.setGeometry(QtCore.QRect(120, 280, 61, 28))
        self.btnsave1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnsave1.setObjectName("btnsave1")
        self.btnupdate1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnupdate1.setGeometry(QtCore.QRect(210, 280, 71, 28))
        self.btnupdate1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnupdate1.setObjectName("btnupdate1")
        self.txtfees = QtWidgets.QLineEdit(self.centralwidget)
        self.txtfees.setGeometry(QtCore.QRect(210, 150, 261, 31))
        self.txtfees.setObjectName("txtfees")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 61, 31))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 61, 31))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 200, 61, 31))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.btnnew1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnnew1.setGeometry(QtCore.QRect(30, 280, 61, 28))
        self.btnnew1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnnew1.setObjectName("btnnew1")
        self.cmbselectstudent = QtWidgets.QComboBox(self.centralwidget)
        self.cmbselectstudent.setGeometry(QtCore.QRect(210, 20, 261, 31))
        self.cmbselectstudent.setObjectName("cmbselectstudent")
        self.txtsubject = QtWidgets.QLineEdit(self.centralwidget)
        self.txtsubject.setGeometry(QtCore.QRect(210, 200, 261, 31))
        self.txtsubject.setObjectName("txtsubject")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1381, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Student Name"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
        self.btndelete1.setText(_translate("MainWindow", "Delete"))
        self.btnsave1.setText(_translate("MainWindow", "Save"))
        self.btnupdate1.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "Date"))
        self.label_3.setText(_translate("MainWindow", "Fees"))
        self.label_4.setText(_translate("MainWindow", "Subject"))
        self.btnnew1.setText(_translate("MainWindow", "New"))
