# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Fees\FeesForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 220, 61, 31))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.dateedit1 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit1.setGeometry(QtCore.QRect(220, 110, 261, 31))
        self.dateedit1.setCalendarPopup(True)
        self.dateedit1.setObjectName("dateedit1")
        self.txtsubject = QtWidgets.QLineEdit(self.centralwidget)
        self.txtsubject.setGeometry(QtCore.QRect(220, 220, 261, 31))
        self.txtsubject.setObjectName("txtsubject")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 171, 31))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 61, 31))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 170, 61, 31))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.cmbselectstudent = QtWidgets.QComboBox(self.centralwidget)
        self.cmbselectstudent.setGeometry(QtCore.QRect(220, 40, 261, 31))
        self.cmbselectstudent.setObjectName("cmbselectstudent")
        self.txtfees = QtWidgets.QLineEdit(self.centralwidget)
        self.txtfees.setGeometry(QtCore.QRect(220, 170, 261, 31))
        self.txtfees.setObjectName("txtfees")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 290, 93, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(110, 290, 93, 28))
        self.btnSave.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnSave.setObjectName("btnSave")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Subject"))
        self.label.setText(_translate("MainWindow", "Select Student Name"))
        self.label_2.setText(_translate("MainWindow", "Date"))
        self.label_3.setText(_translate("MainWindow", "Fees"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
