# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Password_Login_Project\Add_User\Add_User.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 231)
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        MainWindow.setStyleSheet("background-color: rgb(96, 229, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 100, 31))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"gridline-color: rgb(236, 236, 236);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 100, 31))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 100, 31))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtusername = QtWidgets.QLineEdit(self.centralwidget)
        self.txtusername.setGeometry(QtCore.QRect(130, 10, 221, 31))
        self.txtusername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtusername.setObjectName("txtusername")
        self.txtpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword.setGeometry(QtCore.QRect(130, 70, 221, 31))
        self.txtpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword.setObjectName("txtpassword")
        self.txtpassword1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword1.setGeometry(QtCore.QRect(130, 130, 221, 31))
        self.txtpassword1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtpassword1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword1.setObjectName("txtpassword1")
        self.btnregister = QtWidgets.QPushButton(self.centralwidget)
        self.btnregister.setGeometry(QtCore.QRect(130, 180, 93, 28))
        self.btnregister.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnregister.setObjectName("btnregister")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 180, 93, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.btnregister.setText(_translate("MainWindow", "Register"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
